openapi: 3.0.0
info:
  title: Clearlist.io API documentation
  description: Clearlist.io is the ultimate solution for email list cleaning.
  contact:
    name: API Support
    email: hello@clearlist.io
  version: 0.0.1

servers:
- url: https://api.clearlist.io

tags:
  - name: Me
    description: Everything about the user that is using the api
  - name: Email validation
    description: Endpoints used to validate email addresses

components:
  schemas:
    api_key:
      type: object
      properties:
        active:
          type: boolean
          description: Whether the api token is active or not
        name:
          type: string
          description: The name of the api token
        last_used_at:
          type: string
          format: date-time
          description: The last time the api key was used
        created_at:
          type: string
          format: date-time
          description: When the API key was created

    me:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email address of the user
        name:
          type: string
          description: The full name of the user
        uuid:
          type: string
          format: uuid
          description: A unique identifier for the user
        errors:
          type: array
          items:
            type: string
        last_login_at:
          type: string
          description: The last login date of the user
          format: date-time
        time_zone:
          type: string
          description: The time zone for the user
        token:
          type: string
          description: The api token currently in use for the request
        api_keys:
          type: array
          items:
            $ref: '#/components/schemas/api_key'

    email:
      type: object
      properties:
        address:
          type: string
          format: email
          description: The email address
        ok:
          type: boolean
          description: Email is ok for delivery
        risky:
          type: boolean
          description: Email is ok for delivery, but potentially risky to deliver to.
        invalid:
          type: boolean
          description: Email is invalid and should not be delivered to.
        accept_all:
          type: boolean
          description: Whether the email domain accepts all addresses
        is_disposable:
          type: boolean
          description: Whether the email address is part of a disposable address domain
        is_role:
          type: boolean
          description: Whether the email address is identified as a role address (e.g. postmaster@domain.com)
        failed_mx_check:
          type: boolean
          description: The email domain failed the MX check.  It may not have an MX record.
        failed_smtp_check:
          type: boolean
          description: The email address failed the SMTP check and emails cannot be delivered to it.  This may be because the email address is full, amongst other reasons.
        failed_no_mailbox:
          type: boolean
          description: The email address does not exist on the domain
        domain:
          type: string
          description: The email address domain
        canonical:
          type: string
          description: The canonical part of the email address
        messages:
          type: string
          description: Any additional messages about the email verification
        email_state:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          description: A simple state that shows the verification result. 0 = ok, 1 = email is invalid, 2 = email is deliverable but risky, 3 = unknown, 4 = accept all.
        account:
          type: object
          properties:
            credits:
              type: integer
              description: The number of credits remaining in the account.


  securitySchemes:
    clearlist_auth:
      type: apiKey
      in: header
      name: Authorization
      description: The user's bearer token sent via an Authorization header

paths:
  /me:
    get:
      tags:
        - Me
      summary: Get information about the logged in user
      description: Shows all information about the currently logged in user.
      security:
        - clearlist_auth: []
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/me'

        "401":
          description: User could not be found via token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Gives information about what went wrong with the request.

  /api/v1/verify_single_email:
    post:
      tags:
        - Email validation
      summary: Verify a single email
      security:
        - clearlist_auth: []
      parameters:
        - name: email
          in: query
          required: true
          description: The email address to verify
          schema:
            type: string
            format: email
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email'
